### ISSUE TITLE
Port to new yowsup 2.0 version

### ISSUE THREAD

**Issue by stv0g** [stv0g/transwhat#10]
tgalal has continued the development of his yowsup library: https://github.com/tgalal/yowsup

transwhat heavily depends on this library. Yowsup 1.0 is currently broken. Therefore transwhat is not usable anymore.

**Comment by erhan-** [comment]
Just found this by accident and it seems like a nice idea. I was thinking about implementing a simple web interface for whatsapp with the use of yowsup but I guess the idea of making a transport is way better.

Are you still working on this?

Danke!

**Comment by stv0g** [comment]
Hi, it's planned, but I've no capacities to implement this atm.
Feel free to work on it :-)

**Comment by erhan-** [comment]
Later maybe, now it's Klausurphase :P

**Comment by stv0g** [comment]
Exactly! Same is for me :D

**Comment by erhan-** [comment]
I thought so because I saw that you are from RWTH. I'm from RUB but let's put the offtopic to the side ;)
I'm interested in the project and have some free time after that.

**Comment by stv0g** [comment]
Feel free to go for it! I would like to test your stuff, once its ready.

There’s also another feature request which advocates for replacing the Spectrum transport as well.
I would prefer a pure python based solution.

Cheers,

Steffen

Steffen Vogel
Robensstraße 69
52070 Aachen

Mail: post@steffenvogel.de
Mobil: +49 1575 7180927
Web: http://www.steffenvogel.de
Jabber: steffen.vogel@jabber.rwth-aachen.de

**Comment by tgalal** [comment]
Nice we all are in Germany :) Good luck with the exams!

**Comment by moyamo** [comment]
I've been watching this project for a while. I've finally got some free time this weekend. I'll try to work on it then.

**Comment by moyamo** [comment]
On second thought. Have you looked at https://github.com/davidgfnet/whatsapp-purple . It can be used with spectrum2 and libpurple to accomplish the same thing.

**Comment by stv0g** [comment]
Thanks @moyamo! I've merge your port. I recently got into XMPP again. So I'd like to use this transport again.

Maybe we can improve it together..

**Comment by moyamo** [comment]
That'd be great! We might need to dive into the libtransport code to get things like file transfers and proper groupchats to work. Also I realised that I've only used transwhat in gateway-mode. I haven't tested it in server-mode.

**Comment by stv0g** [comment]
> That'd be great! We might need to dive into the libtransport code to get things like file transfers and proper groupchats to work

Unfortunately... I don't really like the mixture of C++ and Python in this project. I was already considering to replace Spectrum by some Python XMPP library (see #5). But most of them don't implement the XMPP component / gateway part in such a nice way as Spectrum does it.

> Also I realised that I've only used transwhat in gateway-mode. I haven't tested it in server-mode.

Oh okay :D I only tested it in server-mode.. Back then..

Btw: Feel free to add me via XMPP: stv0g@0l.de
