### ISSUE TITLE
Replace SQLite with Spectrum backend

### ISSUE THREAD

**Issue by piwats** [stv0g/transwhat#14]
Could it be possible to add PostgreSQL support?

**Comment by moyamo** [comment]
It could be possible, I can probably try this weekend. Is PostgreSQL very different from MySQL in Syntax?

**Comment by piwats** [comment]
It's SQL. There are some differences. Python should handle it vie psycopg2 (http://initd.org/psycopg/docs/), though.

**Comment by vitalyster** [comment]
In fact spectrum plugin should not use database directly and should reuse frontend database via protobuf, https://github.com/hanzz/libtransport/issues/59 - it should be very easy to extend spectrum protocol for it.

**Comment by piwats** [comment]
If libtransport is going to have a backend api, would it then be possible to get transwhat db agnostic?

**Comment by moyamo** [comment]
According to the docs libtransport currently supports sqlite3, mysql and postgresql.

**Comment by stv0g** [comment]
@vitalyster Okay, thats the way to go. I changed to title of the issue.

In general, I'd like to keep things a simple as possible. This is a way to do so.
Thanks for the tip!

**Comment by moyamo** [comment]
Do you think we should just add support for SQLite? Yowsup already uses SQLite so I think we might as well. I'm not so sure how flexible generic Storage API will be.

**Comment by piwats** [comment]
May I ask about the status of this?

**Comment by moyamo** [comment]
@hanzz mentioned that he might have time to implement the [Backend API](hanzz/spectrum2#59) on Tuesday. I will wait until then. If that does not happen, I will try integrating PostgreSQL with transwhat (or more likely: Use a DB-agnostic python library).

**Comment by piwats** [comment]
@moyamo thank you very much :)

**Comment by moyamo** [comment]
If the Backend API, doesn't pan out, a quick google search shows these DB-agnostic SQL APIs: [SQLAlchemy](http://www.sqlalchemy.org/), [peewee](http://docs.peewee-orm.com/en/latest/), [PonyORM](https://docs.ponyorm.com/firststeps.html#defining-entities), [SQLObject](http://www.sqlobject.org/).

@stv0g I like the look of PonyORM. If we have to support other databases what API do you think we should use?

**Comment by stv0g** [comment]
> If the Backend API, doesn't pan out, a quick google search shows these DB-agnostic SQL APIs: SQLAlchemy, peewee, PonyORM, SQLObject.
> 
> @stv0g I like the look of PonyORM. If we have to support other databases what API do you think we should use?

I would keep it as simple as possible. Apart from that, I am not really familiar with that. Feel free to choose your favourite one.

We should make sure that its easy to install. `pip install xxx` should do it.

**Comment by piwats** [comment]
@moyamo thank you very much!

Thanks a lot!
