### ISSUE TITLE
Docker support?

### ISSUE THREAD

**Issue by jacknife1** [stv0g/transwhat#16]
I wonder if you have thought of making a docker image for this project. It would be very useful. Take a look at https://github.com/tgalal/yowsup-docker for an example.

**Comment by stv0g** [comment]
Spectrum also provides a [Dockerfile](https://github.com/hanzz/spectrum2/blob/master/Dockerfile).

In my opinion, I makes more sense the use the Spectrum Dockerfile as a base image and add transwhat on top of it.

Having the Yowsup 2 library in a Docker container does not really make sense to me. @tgalal is using the Docker container to provide the CLI

**Comment by stv0g** [comment]
Additionally, we can think about using docker-compose to orchestrate all the components which are required:

- XMPP Server: https://hub.docker.com/r/prosody/prosody/
- Spectrum: https://hub.docker.com/r/spectrum2/spectrum2/
- Database: we dropped the mysql requirement :-) So we don't need a container for this anymore

**Comment by moyamo** [comment]
Maybe we should try to include transwhat in spectrum? Similar to how the libpurple plugin comes with spectrum.

**Comment by moyamo** [comment]
Is tgalal's docker container for yowsup? I can't find it :)

**Comment by stv0g** [comment]
There's a link in the first post.

**Comment by moyamo** [comment]
I just made a [Dockerfile](https://gist.github.com/moyamo/5bfd8796d79d6d4e22ed) based on spectrum. It doesn't come with prosody though. This makes it a bit awkward to setup. Also it doesn't work because the version of yowsup installed by pip just became outdated.
https://github.com/tgalal/yowsup/issues/1164

**Comment by moyamo** [comment]
My attempt to get the docker image for prosody to work failed miserably. Maybe someone else could get it working?

**Comment by stv0g** [comment]
Yes i will try it this evening :-)

Using docker-compose...

**Comment by hanzz** [comment]
I plan to include transwhat in my docker image, just have to find out best way how to actually install it :)

**Comment by hanzz** [comment]
By "my docker image" I mean the official Spectrum 2 image.

**Comment by stv0g** [comment]
I pushed my current state to the [docker](https://github.com/stv0g/transwhat/tree/docker) branch.

I haven't tested it extensively. So any feedback and/or patches are welcome!

**Comment by stv0g** [comment]
I'll discard by branch because it does not make sense to have another Dockerfile for transwhat.

There is already one by the spectrum project which includes support for transWhat:

https://github.com/hanzz/spectrum2/blob/master/Dockerfile
