### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by stv0g** [stv0g/transwhat#17]
We really need a INSTALL.md to show people on how to get started.
I get a couple of requests per month about this.
Please use this issue to collect some pieces of information for this guide.

**Comment by genesis231** [comment]
I'm Still confused. Does this code transport whatsapp messages to xmpp network?

**Comment by moyamo** [comment]
Yes. You need to register your XMPP account with transwhat server. Then you can send and receive messages to and from your whatsapp contacts.

**Comment by genesis231** [comment]
ok thank you. Nice work.

**Comment by stv0g** [comment]
I started adding some basic installations instructions to the [README.md](https://github.com/stv0g/transwhat/blob/yowsup-2/README.md) file

**Comment by genesis231** [comment]
Can u update README.md, for executing transwhat.py. How to pass arguments from command line. Also, further steps after executing transwhat.py (xmpp service discovery from pidgin).
Plz specify.

**Comment by moyamo** [comment]
@genesis231 I updated [USAGE.md](https://github.com/stv0g/transwhat/blob/yowsup-2/USAGE.md) with instructions on how to run transwhat. If you need more detail just ask.

**Comment by stv0g** [comment]
Thanks @moyamo for adding this! I extended your descriptions a little bit.

As soon as I find some time, I will create two little screencasts explaining the setup and the usage (with Pidgin).

**Comment by genesis231** [comment]
@moyamo, bro need more documentation & @stv0g adding screenshot will help.

**Comment by stv0g** [comment]
@genesis231 The details provided by @moyamo should be sufficient.
You should start reading the [Spectrum documentation](http://spectrum.im/documentation/admin.html) first!

**Comment by moyamo** [comment]
@genesis231 At which point are you stuck?
