### ISSUE TITLE
How to compile latest Spectrum2 version

### ISSUE THREAD

**Issue by genesis231** [stv0g/transwhat#18]

**Comment by moyamo** [comment]
You should probably ask for help at
(https://github.com/hanzz/spectrum2).

You look like you getting permission errors. Check the filesystem
permissions of your directories.

**Comment by stv0g** [comment]
This is unrelated to transWhat. Please report it to the transWhat developers. But it most probably a misconfiguration of you system. So you can try it at Stackoverflow as well.
