### ISSUE TITLE
Registration not supported?

### ISSUE THREAD

**Issue by stv0g** [stv0g/transwhat#24]
I have a problem, that I am not able to register with the transport (Spectrum2 is running in gateway mode).
Does anyone have tried this so far?

    2015-12-06 13:52:23,749 INFO  Component.RAW: RAW DATA IN <iq type='get' to='whatsapp.0l.de' from='stv0g@0l.de/cam' id='purpleb5f62d29'><query xmlns='jabber:iq:register'/></iq>
    2015-12-06 13:52:23,750 INFO  Component.RAW: RAW DATA OUT <iq from="whatsapp.0l.de" id="purpleb5f62d29" to="stv0g@0l.de/cam" type="error"><error type="cancel"><feature-not-implemented xmlns="urn:ietf:para

**Comment by moyamo** [comment]
I think your just supposed to login without registering in gateway mode.

**Comment by stv0g** [comment]
Okay, I am using Adium (libpurple based) on OS X. How do I login to the transport?
Registration does not really makes sense here. You are right. We might want to use the registration later on to register a new number with Yowsup..

I tried to add a new buddy with the JID of my transport. But how do I specify my WhatsApp credentials?

**Comment by stv0g** [comment]
Somehow there must be a mechanism to translate between my JID and my WhatsApp mobile no

**Comment by moyamo** [comment]
Oh wait. I thought you were using server mode. In gateway mode you have to register with the transport. To do that you have to go through service discovery. I'm not sure if Adium supports service discovery. You only have to register once. I know Gajim supports service discovery and Pidgin supports it with an extension.

**Comment by stv0g** [comment]
Yes, I went through service discovery and tried to register. There the server (Prosody) and the transport (Spectrum) responded with: "feature-not-supported" (the registration).

Can you send me your Spectrum backend config?
According to the Spectrum source code, the registration is handled completely in the Spectrum core, not the backend..

**Comment by vitalyster** [comment]
database=none?

**Comment by stv0g** [comment]
@vitalyster In Spectrum? I configured mySQL as the database backend. But Spectrum does not seem to fill the database...

**Comment by moyamo** [comment]
It's essentially this https://github.com/moyamo/transwhat-quickinstall/blob/master/transwhat.cfg

**Comment by stv0g** [comment]
Got it:

    2015-12-06 13:51:42,634 WARN  Spectrum: Registrations won't work, you have specified [database] type=none in config file.

**Comment by moyamo** [comment]
c40d4776
