### ISSUE TITLE
Send MUC feature to Spectrum

### ISSUE THREAD

**Issue by dazzzl** [stv0g/transwhat#28]
The result from the discussion with HanzZ on Spectrum MUC:

Problem: no Transwhat MUC support in Gjaim 

Possible Solution: send feature muc=true also inside this message to Spectrum:
plugin.handleBackendConfig('features', 'send_buddies_on_login', 1)

**Comment by dazzzl** [comment]
def handleBackendConfig(self, section, key, value): 

in backend.py has to be modified to handle more than one feature

**Comment by moyamo** [comment]
Fixed
