### ISSUE TITLE
double "message" when sending pic in wa group

### ISSUE THREAD

**Issue by thundergreen** [stv0g/transwhat#34]
when sending a pic in wa group it will be resend to me:

![screenshot_2015-12-30-10-55-07](https://cloud.githubusercontent.com/assets/13320319/12049196/6afa15b0-aee4-11e5-9152-0107d94b2789.png)

**Comment by moyamo** [comment]
Conversations bug: https://github.com/siacs/Conversations/issues/1635#event-506981199
