### ISSUE TITLE
only tel numbers in group chat, even if contact (number) added

### ISSUE THREAD

**Issue by thundergreen** [stv0g/transwhat#35]

**Comment by moyamo** [comment]
Are all group participants' nicknames numbers or only some of them numbers? I may have fixed this yesterday. Try pulling the latest version.

**Comment by thundergreen** [comment]
All of them are numbers even after adding some numbers to my contacts ....
I tried a new transwhat version this morning .. It didn't work.dunno the
exact error message but it was something with Unicode error line 135 in
session php

Thorsten Fröhlich
Am 31.12.2015 13:49 schrieb "Mohammed Yaseen Mowzer" <
notifications@github.com>:

**Comment by thundergreen** [comment]
The only participant with name is me in the wa group

Thorsten Fröhlich
Am 31.12.2015 13:49 schrieb "Mohammed Yaseen Mowzer" <
notifications@github.com>:

**Comment by moyamo** [comment]
Please attach the debug logs. It will be helpful in finding the error.

**Comment by thundergreen** [comment]
Will do though. I'm now on my way to Germany .. Happy new year and see u
soon ;)

Thorsten Fröhlich
Am 31.12.2015 14:05 schrieb "Mohammed Yaseen Mowzer" <
notifications@github.com>:

**Comment by NeoBelerophon** [comment]
I debugged around a little and found that atleast with spectrum2 the handleBuddies(self, buddies) is never called on login. So buddy list is empty and only numbers and no names appear in groupchats

**Comment by moyamo** [comment]
@NeoBelerophon  Which version of spectrum2 are you using?

**Comment by NeoBelerophon** [comment]
at the moment 2.0.0~beta2-805-g51746c5~wheezy
is it too old?

**Comment by moyamo** [comment]
Yes, 2.0.0 has been released. But the problem may still persist.

**Comment by NeoBelerophon** [comment]
ok after update to lastest github version of spectrum2 it works :+1:

**Comment by moyamo** [comment]
@thundergreen if you don't have this problem anymore. I'm going to close this issue.

**Comment by thundergreen** [comment]
i guess u can close it.. seems to work atm

2016-01-08 9:52 GMT+01:00 Mohammed Yaseen Mowzer <notifications@github.com>:
