### ISSUE TITLE
Discovery does not work	

### ISSUE THREAD

**Issue by BartS23** [stv0g/transwhat#47]
Hello,

I try to install this transport on Ubuntu Server 15.10 (Kernal 4.2.0-27).
I've installed prosody (Version 0.9.8), spectrum2 (Version 2.0.1-git-e921269) and transwhat (Version: today).

Here the config files:
[prosody.cfg.lua](https://github.com/stv0g/transwhat/files/116082/prosody.cfg.lua.txt)
[whatsapp.cfg](https://github.com/stv0g/transwhat/files/116083/whatsapp.cfg.txt)

As Client i use Gajim (Version 0.16.5).

If I connect to the server an try to discover the services i get no response.
![gajim](https://cloud.githubusercontent.com/assets/10829389/12791112/d3ec8d28-caa5-11e5-8adf-49d755b9d2b0.png)

If I change the adress of the server to whatsapp.0l.de i get the following error message:
![gajim2](https://cloud.githubusercontent.com/assets/10829389/12791118/dab7acc8-caa5-11e5-8a36-46d51986ae89.png)

> **The service is not browsable**
> This type of service does not contain any items to browse.

Attached the logs from prosody and spectrum2.
I don't see any error. 

regards
[prosody.log.txt](https://github.com/stv0g/transwhat/files/116089/prosody.log.txt)
[spectrum2.log.txt](https://github.com/stv0g/transwhat/files/116090/spectrum2.log.txt)

**Comment by moyamo** [comment]
You need to enter the domain name of *your* server; the server transwhat and prosody is installed on.

**Comment by BartS23** [comment]
Hello,

if I enter the correct Servername (xmpp.example.com is only a placeholder), I get no response from the Server:
![gajim](https://cloud.githubusercontent.com/assets/10829389/12791112/d3ec8d28-caa5-11e5-8adf-49d755b9d2b0.png)

**Comment by stv0g** [comment]
We can not reproduce this issue. It is probably a misconfiguration of your XMPP server or Spectrum2

**Comment by BartS23** [comment]
Just for the Documentation:
The domain of the transport MUST be a subdomain from the XMPP server.
XMPP: xmpp.example.org
transwhat: whatsapp.xmpp.example.org

**Comment by stv0g** [comment]
Usually your XMPP server should automatically forward the auto discovery entries from transWhat to you.
