### ISSUE TITLE
Find alternative for Spectrum

### ISSUE THREAD

**Issue by stv0g** [stv0g/transwhat#5]
We should look out for a Spectrum alternative.

I dont like this mixture of C++ and Python code which communicate via Google protobuf.

It's error prone and limiting the available features of XMPP

**Comment by stv0g** [comment]
I'm pondering to port transWhat to SleekXMPP which is a generic XMPP library written completely in Python. It's nicely coded and still actively maintained and improved.

It already has a simple example of a XMPP component:
https://github.com/fritzy/SleekXMPP/blob/develop/examples/echo_component.py

**Comment by stv0g** [comment]
It would be nice to hear @moyamo and @dazzzl's opinion about this as they are contributing a lot lately.

**Comment by moyamo** [comment]
I think it will be nicer to stay with spectrum and work with them. Spectrum is becoming and multi-protocol transport. They just added support for [Slack](https://slack.com/) as an alternative to XMPP. And I think it will be a lot easier than reading all the XEPs to implement an independent transport.

**Comment by stv0g** [comment]
Yes, I was quite surprised to see the Spectrum 2 be quite active lately.
Last time I checked their status it was nearly dead and looking for new devs.

Personally, I have a problem using two languages in this project: C++ for Spectrum and Python for transWhat.
It would be much nicer to have a fully consistent and clean C++ or Python implementation.
I was thinking about implementing transWhat in C++. There's already [whatsapp-purple](https://github.com/davidgfnet/whatsapp-purple) which does this. 
It's already usable with Spectrum by using the libpurple backend.

(This was basically the reason I stopped working on transWhat because I didn't saw the point to work on another approach which is not as clean as using purple-whatsapp.)

**Comment by moyamo** [comment]
I was using whatsapp-purple too for a long time, but I couldn't get groupchats to work. I would argue that transwhat is actually cleaner. It was built to be compatible with spectrum, whereas whatsapp-purple was not. Groupchats were hard to get working since the libpurple plugin and whatapp-purple do not interact properly and t was unclear where the problem was. Maybe we can both work to get the libpurple plugin and whatsapp purple inline? :)

**Comment by stv0g** [comment]
What do you mean by "get them inline" ? Into the tree of the spectrum2 repo?

**Comment by moyamo** [comment]
No, just make them work better together. The thing is, libpurple assumes it's working directly with a client while with spectrum you're working over XMPP. When you receive a groupchat message, whatsapp-purple just opens a new groupchat "window". This won't work over XMPP as there is no way to force a client to open a new chat.

Also as far as I know. MUCs is not implemented in the libpurple plugin properly either.

I'm not sure how to reconcile these behaviours.

**Comment by stv0g** [comment]
I agree. :-)
