### ISSUE TITLE
Download of encrypted media to local directory and provide a link to it

### ISSUE THREAD

**Issue by dazzzl** [stv0g/transwhat#54]
I played with a combination of tgalal's latest yowsup version and jlguardi's. You find that in my repo. 
For this a made an experimental Transwhat,  which fixed the Unicode bug and download encrypted images.  However,  it is very dirty and it would be good if we would read the server path and URL from the Transwhat config. Spectrum support this for libpurple backends, like facebook. Even if youwsup is changing the api , we need such a kind of downloading to the local server.

**Comment by stv0g** [comment]
Hi @dazzzl!

What do you think about using [XEP-0363](http://xmpp.org/extensions/xep-0363.html) for the decrypted media contents?

Most people are using Prosody or ejabberd which are providing support for this XEP:

- https://modules.prosody.im/mod_http_upload.html

**Comment by dazzzl** [comment]
This would be a possibility. However, the support of http_upload is then required. Not all server installation provide this. Furthermore,  it is more complicated to implement this.

**Comment by stv0g** [comment]
Sure, I agree.

Is there support from Spectrum to send media as payload of an XMPP stanza?
I know that there are some other XEPs (Jingle?) which standardize something like that.

But http_upload has several advantages over those..

**Comment by moyamo** [comment]
We could use something like [SimpleHTTPServer](https://docs.python.org/2/library/simplehttpserver.html#module-SimpleHTTPServer) to serve http from the transwhat server.

**Comment by stv0g** [comment]
:-/ I don't like to make transwhat more complex with things like that.

In my opinion the HTTP Upload XEP is the way to go.
Alternatively, Spectrum also supports file transfers. So we could transfer the image this way..

**Comment by moyamo** [comment]
I don't think spectrum does support file transfer.

**Comment by stv0g** [comment]
See https://github.com/hanzz/spectrum2/blob/master/plugin/python/NetworkPlugin.py#L187

**Comment by moyamo** [comment]
Last time I checked that was broken, but maybe they fixed it. I will ask on the chat room.

**Comment by dazzzl** [comment]
My suggestion was the usage of this feature...

http://spectrum.im/documentation/configuration/web_storage.html

we have to read out the transport config and store the file in the corresponding directory and provide the corresponding link ...

**Comment by moyamo** [comment]
Do we have to run our own webserver?

**Comment by moyamo** [comment]
I wrote a parser for the configuration file. #56

**Comment by stv0g** [comment]
I would make it optional. Maybe by using another entry in the config.

What do you think about using the `[transwhat]` section for that:

```ini
[transwhat]
enable_httpd = 1
```

**Comment by dazzzl** [comment]
Download encrypted images to the web storage folder:

https://github.com/dazzzl/transwhat

I haven't tested it completely ... but, what do you think?

**Comment by stv0g** [comment]
I merged your improvements in a1b8cf0ca91022fe6f59df82dd71bae7ed5a9e4a
