### ISSUE TITLE
BeautifulSoup, a dependency of e4u, is not supported in latest Python version

### ISSUE THREAD

**Issue by dariox86** [stv0g/transwhat#55]
Installing e4u in Parabola GNU/Linux, a fork of Arch Linux, gives the following result:

```
`[dario@quadcore transwhat]$ sudo pip install --pre e4u
Requirement already satisfied (use --upgrade to upgrade): e4u in /usr/lib/python3.5/site-packages/e4u-0.2rc1-py3.5.egg
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/lib/python3.5/site-packages (from e4u)
Collecting BeautifulSoup (from e4u)
  Using cached BeautifulSoup-3.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-q1sei75c/BeautifulSoup/setup.py", line 22
        print "Unit tests have failed!"
                                      ^
    SyntaxError: Missing parentheses in call to 'print'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-q1sei75c/BeautifulSoup/`
```

Actually there should be an updated version of said library for Python 3, but e4u still depends on the old version.

**Comment by moyamo** [comment]
Hi dariox86, since whatsapp just recently rolled out end-to-end encryption, transwhat is mostly broken. We are in the process of fixing it. I think for future releases we will no longer use e4u.

**Comment by dariox86** [comment]
I understand. I was wondering how did you manage to use it with this inconvenience. So, are you telling me that at the moment it is useless for me to try to get it up and running as it is severely broken?

**Comment by moyamo** [comment]
Yeah, we should be able to get it working in about a week.

**Comment by dariox86** [comment]
OK. Thank you!

**Comment by stv0g** [comment]
Is transwhat supported on Python 3.5? o_O Never tested it :D

Please use Python 2.7 for now.

And regarding `e4u`: As pointed out, I don't think WhatsApp is still using the Softbank encoding for emojis. We can try it with the standard UTF-8 encoding.
Maybe this emoji package might be nice: https://pypi.python.org/pypi/emoji/

**Comment by dariox86** [comment]
OK, I'll try with Python 2.7 when it is in a working state again. Thank you.

**Comment by stv0g** [comment]
A little follow-up:

In tgalal/yowsup#529 it is stated that WhatsApp still uses the soft bank encoding for emojis.

As said, we currently rely on e4u and therefore are restricted to Python 2.7.

In the future, we might drop the e4u dependency and parse the [XML data](https://github.com/lambdalisue/e4u/blob/master/e4u/data/emoji4unicode.xml) which is used by e4u directly.

**Comment by msva** [comment]
is it any progress on de-e4u'ing (and moving to be py3-compatible)? :)
// JFYI: py2.7 is almost EOL...
