### ISSUE TITLE
Error YowAxolotlLayer after yowsup2 release new version (2.5.0)

### ISSUE THREAD

**Issue by noob2020** [stv0g/transwhat#60]
File "/opt/transwhat/yowsupwrapper.py",line 10, in <module>
  from yowsup.layers.axolotl                    import YowAxolotlLayer
ImportError: cannot import name YowAxolotlLayer

help please....

**Comment by silberzwiebel** [comment]
I ran into this issue, too. I'm pretty sure it is related to [this issue at yowsup](https://github.com/tgalal/yowsup/issues/1611)

**Comment by psx01de** [comment]
Hi, whats the solution?

**Comment by btlzdrav** [comment]
I ran into this too. Can someone provide a solution?

**Comment by varnav** [comment]
Try updating yowsupwrapper.py with new version: https://raw.githubusercontent.com/rigid/transwhat/5063966772a7892261479a5e9af1541512eab4a3/yowsupwrapper.py

**Comment by psx01de** [comment]
Thanks, works with this
