### ISSUE TITLE
ImportError: cannot import name YowAxolotlLayer

### ISSUE THREAD

**Issue by aiomaster** [stv0g/transwhat#61]
```
  File "/usr/src/transwhat/yowsupwrapper.py", line 10, in <module>
    from yowsup.layers.axolotl                                     import YowAxolotlLayer
```

It is not possible to run transwhat with newer yowsup2 cause they changed their internal structure, I think.
See https://github.com/tgalal/yowsup/issues/1658

**Comment by stv0g** [comment]
Should be fixed by #59
