### ISSUE TITLE
ImportError: No module named config

### ISSUE THREAD

**Issue by Nicos-git** [stv0g/transwhat#73]
Hi,

I'm getting this error with latest yowsup-2 branch.

> ImportError: No module named config
> Traceback (most recent call last):
>   File "/opt/transwhat/transWhat/transwhat.py", line 41, in <module>
>     from config import SpectrumConfig

I got it fixed by using a symbolic link into the "transwhat"-directory.
Does anybody know if there is an other solution for this?

Thanks a lot!

**Comment by stv0g** [comment]
Thanks for reporting. I hope I fixed the issue.
The fix is untested. Please re-open if it still fails.

**Comment by Nicos-git** [comment]
Works fine, thanks a lot!
👍

**Comment by ConiKost** [comment]
Hm, I've applied this fix for me, but it seems still to fail for me :/

Traceback (most recent call last):
  File "/usr/lib/python-exec/python2.7/transwhat", line 11, in <module>
    load_entry_point('transwhat==0.2.2', 'console_scripts', 'transwhat')()
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 570, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 2409, in load
    return self.resolve()
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 2415, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib64/python2.7/site-packages/transWhat/transwhat.py", line 41, in <module>
    from Spectrum2.config import SpectrumConfig
ImportError: No module named config

**Comment by Nicos-git** [comment]
Hi @ConiKost 
did you reinstall transwhat ("python setup.py install")?
If yes, maybe you need to remove the old transwhat installation first (it seems like you've got two transwhat installations).

**Comment by ConiKost** [comment]
Hi @Nicos-git,
no, it's a fresh install. I've took 0.2.2 and applied this fix here before installation.

**Comment by HoSnoopy** [comment]
I have the same problem, but I connot find a solution. Where exactly I have to put the symbolic link?

**Comment by stv0g** [comment]
Hi @HoSnoopy,

did you used my latest version (Not the one installed via `pip`)?

**Comment by HoSnoopy** [comment]
Yes. With pip, and I also tried git clone and python setup.py install. Both didn't work with this error.
