### ISSUE TITLE
This Still Work?

### ISSUE THREAD

**Issue by QomariSanjaya** [stv0g/transwhat#79]
Hello, i dont know where to ask, so i ask here.
Is this plugin still work? I use it in my Jabber server + Spectrum 2, and the instance is running. But how i can get Whatsapp password to register?

**Comment by pr0j3ctx** [comment]
Same question. Is there anyway to Register WhatsApp with transwhat?

**Comment by stv0g** [comment]
Yes, this transport is still actively used and developed.

Please have a look at the [installation](https://github.com/stv0g/transwhat/blob/yowsup-2/INSTALL.rst) and [usage](https://github.com/stv0g/transwhat/blob/yowsup-2/USAGE.rst) instructions for details.
