### ISSUE TITLE
No module named threadutils

### ISSUE THREAD

**Issue by evgenyh** [stv0g/transwhat#84]
hi, tried to install this now on centos 7. all went ok. but once this transport being started, I getting a bunch of these errors: 
`Traceback (most recent call last):
  File "/usr/bin/transwhat.py", line 5, in <module>
    pkg_resources.run_script('transwhat==0.2.2', 'transwhat.py')
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 540, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1455, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/lib/python2.7/site-packages/transwhat-0.2.2-py2.7.egg/EGG-INFO/scripts/transwhat.py", line 36, in <module>
    import threadutils
ImportError: No module named threadutils`

**Comment by SmartHoneybee** [comment]
Try this:
```diff
--- a/transWhat/transwhat.py
+++ b/transWhat/transwhat.py
@@ -33,13 +33,13 @@ import asyncore
 import sys, os
 import e4u
 import Queue
-import threadutils
+import transWhat.threadutils
 
 sys.path.insert(0, os.getcwd())
 
 from Spectrum2.iochannel import IOChannel
 from Spectrum2.config import SpectrumConfig
-from whatsappbackend import WhatsAppBackend
+from transWhat.whatsappbackend import WhatsAppBackend
 from yowsup.common import YowConstants
 from yowsup.stacks import YowStack
```

**Comment by stv0g** [comment]
Hi @SmartHoneybee ,

should we apply this path to the repo?

**Comment by SmartHoneybee** [comment]
Hello @stv0g,

the patch fixed the issue for me, so I'd say yes.
In the end it is your project, so do whatever you want to.

Bee
