### ISSUE TITLE
Support chat is down

### ISSUE THREAD

**Issue by truenicoco** [stv0g/transwhat#88]
I don't think that `conference.0l.de` is still running. Pretty sad because I would have been happy to have some support, or at least to know if it is still supposed to work.

**Comment by Natureshadow** [comment]
> I don't think that `conference.0l.de` is still running. Pretty sad
> because I would have been happy to have some support, or at least to
> know if it is still supposed to work.

I am connected to the MUC, and I see other users as well.

**Comment by truenicoco** [comment]
Well this is very strange, I tried from 2 different locations (Israël and France), and with 2 different XMPP servers (my own and the one from my work), and I could never connect to conference.0l.de

After ~30 seconds I have an error message stating that the MUC doesn't exist.

**Comment by thundergreen** [comment]
Network not reachable

**Comment by stv0g** [comment]
`conference.0l.de` is running on a machine in my basement and sitting behind a VPN / NAT.

I will look into it. Maybe you are using a difference port than 5222?

**Comment by vitalyster** [comment]
@stv0g you need to forward 5269 (s2s) port, not 5222(c2s)

**Comment by stv0g** [comment]
Mhh, I already forwarded that port...
Maybe some people are using IPv6 which might be broken..

```
-A PREROUTING -p tcp --dport 5269 -j DNAT --to-destination XXXXXX
-A PREROUTING -p tcp --dport 5222 -j DNAT --to-destination XXXXXX
```

**Comment by stv0g** [comment]
I will migrate my Prosody to a public instance in a few days.. This should solve the issue..

Until this is done, feel free to join the Spectrum MUC: spectrum@conference.spectrum.im
