### ISSUE TITLE
transwhat backend does not work

### ISSUE THREAD

**Issue by o---** [stv0g/transwhat#90]
Hi, 

I am seeking for a guidance or help as I don't know whether this is an issue or a misconfiguration at my end. 

I have been following many different guides I found all over the internet on how to configure whatsapp for prosody using spectrum2 and transwhat. None of them has lead me into a solution. 

As a client I use latest version of Gajim and I can see in service discovery my whatsapp domain, but its not giving me any options:

![obrazok](https://user-images.githubusercontent.com/5457048/38084016-a28d592c-334b-11e8-9dc1-f4e0ec6d023b.png)

In the spectrum2.log I see this:

![obrazok](https://user-images.githubusercontent.com/5457048/38091258-4b3a7d52-3365-11e8-90b6-d927c767c79a.png)

And my backend.log is completely empty. 
![obrazok](https://user-images.githubusercontent.com/5457048/38091310-784905de-3365-11e8-8de5-74eb49c33ee6.png)

my whatsapp sub domain resolves to the server prosody, spectrum and transwhat are all installed on:
![obrazok](https://user-images.githubusercontent.com/5457048/38091441-dfd147fc-3365-11e8-9ccf-d0aa4790e793.png)

All my backends are listening on port 5347. I have other backends besides transwhat. 
![obrazok](https://user-images.githubusercontent.com/5457048/38091540-2077cd26-3366-11e8-8cee-7f5725ca9e4a.png)

As server software I am using the sangoma FreeBPX 64bit distro plain and standard as it comes with prosody installed on top. 

When I execute:
/usr/bin/transwhat --host localhost --port 30908 --service.backend_id=1 "-j" "whatsapp.domain.tld" "/etc/spectrum2/transports/whatsapp.cfg"

I get:
![obrazok](https://user-images.githubusercontent.com/5457048/38097342-67c4c4ea-3375-11e8-85d1-bcc13dbf11e3.png)

Python version is 2.7.5.

Thanks in advance.

**Comment by o---** [comment]
Removing 

`from __future__ import unicode_literals`

from **backend.py** has resolved the issue with Python 2.7.5.

**Comment by stv0g** [comment]
Python 2 is not supported
