### ISSUE TITLE
Bot type bridging?

### ISSUE THREAD

**Issue by poVoq** [stv0g/transwhat#94]
It seems like this is more of an personal bridge, correct?

How about adding a bot mode similar to how Matterbridge (https://github.com/42wim/matterbridge) does for other chats, i.e. add one WhatsApp user that coss-posts the messages from many users by automatically adding their username in front of the message.

This would be probably useful for group-chats and to allow people without their own WhatsApp account to participate in group-chats.

**Comment by stv0g** [comment]
No transWhat can bridge for multiple users. It is implemented as an XMPP component using Spectrum.

Matterbridge uses a different approach which is not compatible with Spectrum.
The idea is still interesting though. This would be part of a different project..
