### ISSUE TITLE
Error submitting registration form.

### ISSUE THREAD

**Issue by Cego1200** [stv0g/transwhat#95]
As soon as I enter my phone number i get a error requester telling me:

"Error submitting registration form
Reason: Not acceptable
The recipient or server understands the request but is refusing to process it because it does not meet criteria defined by the recipient or server (e.g. local policy regarding acceptable words in messages)."

Please help

**Comment by stv0g** [comment]
This is most likely due to some problems in yowsup. Keeping yowsup uptodate becomes hard and harder.
