### ISSUE TITLE
[Q] Project status?

### ISSUE THREAD

**Issue by Megver83** [stv0g/transwhat#98]
There hasn't been much activity in the last year, here in the issue tracker and in the code itself. However, it doesn't seem to be completely dead (yet); just saying as yowsup is having some troubles with WhatsApp blocking their numbers (temporary solution to get the WhatsApp password is by extracting it from the app, e.g. [like this](https://stackpointer.io/security/extract-whatsapp-password-android/374/)) and its dev doesn't know if it will ever work again, and idk how will that affect transwhat.

Are there going to be new releases this year? the last one was in 2017, and I wonder if the yowsup-3 branch is already working or if it needs some more work to do.

**Comment by stv0g** [comment]
Hi @Megver83,

the development has stalled for a few years now. I dont intent to pick it up anytime soon.

However, I am very open support others in doing so.

Cheers,
Steffen
